baseURL = "/"
languageCode = "en-us"
title = "Megakit"
summaryLength = 10
relativeURLs = true
canonifyURLs = true

[pagination]
  pagerSize = 20
  path = "/"

[taxonomies]
  category = "categories"

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
  unsafe = true

[module]
  replacements = "local/component-library -> ../component-library"

[[module.imports]]
  path = "local/component-library"

[[module.imports]]
  path = "github.com/cloudcannon/bookshop/hugo/v3"
